name: Keeper Secrets Manager Github Action
on:
 workflow_dispatch:

jobs: 
 ksm-test-random:
  runs-on: ubuntu-latest

  steps:
   - name: Retreive Secrets From KSM
     id: ksecrets
     uses: Keeper-Security/ksm-action@master
     with:
       keeper-secret-config: ${{ secrets.PAMPASS }}
       secrets: |
        9SvyI_7rsdhleca9zWrvHA/field/password > pwd
        9SvyI_7rsdhleca9zWrvHA/field/password > env:pwd

   - name: View password
     run: |
      echo 'pwd: ${{steps.ksecrets.outputs.pwd }}'
   
