name: Keeper Secrets Manager Github Action
on:
 workflow_dispatch:

jobs: 
 ksm-test-random:
  runs-on: ubuntu-latest

  steps:
   - name: Retreive Secrets From KSM
     id: ksecrets
     uses: Keeper-Security/ksm-action@master
     with:
       keeper-secret-config: ${{ secrets.PAMKEY }}
       secrets: |
        teyUQ49ZZLeAq-LZku2xIQ/field/password > pwd
        teyUQ49ZZLeAq-LZku2xIQ/field/password > env:pwd
        teyUQ49ZZLeAq-LZku2xIQ/field/login > lng
        teyUQ49ZZLeAq-LZku2xIQ/field/login > env:lng
        teyUQ49ZZLeAq-LZku2xIQ/file/1key.png > file:/tmp/1key.png

   - name: View login
     run: |
      echo "password: ${{ env.pwd }}"
      echo "login: ${{ env.lng }}"
      
   
