name: Keeper Secrets Manager Github Action
on:
 workflow_dispatch:

jobs: 
 ksm-test-random:
  runs-on: ubuntu-latest

  steps:
   - name: Retreive Secrets From KSM
     id: ksecrets
     uses: Keeper-Security/ksm-action@master
     with:
       keeper-secret-config: ${{ secrets.  }}
       secrets: |
         UID/field/password > pwd

   - name: View password
     run: |
      echo 'pwd: ${{steps.ksecrets.outputs.pwd }}'
   
